using System.Security.Cryptography;
using DevQualX.Domain.Infrastructure;
using DevQualX.Functional;

namespace DevQualX.Application.Authentication;

/// <summary>
/// Initiates the OAuth flow with GitHub using PKCE.
/// </summary>
public class InitiateOAuth(IGitHubOAuthService gitHubOAuthService) : IInitiateOAuth
{
    /// <inheritdoc />
    public Task<Result<OAuthInitiationResult, Error>> ExecuteAsync(
        string redirectUri,
        string? state = null,
        CancellationToken cancellationToken = default)
    {
        // Validate redirect URI
        if (string.IsNullOrWhiteSpace(redirectUri))
        {
            return Task.FromResult<Result<OAuthInitiationResult, Error>>(new ValidationError
            {
                Message = "Redirect URI is required",
                Code = "AUTH001",
                Errors = new Dictionary<string, string[]>
                {
                    [nameof(redirectUri)] = ["Redirect URI cannot be empty"]
                }
            });
        }

        if (!Uri.TryCreate(redirectUri, UriKind.Absolute, out _))
        {
            return Task.FromResult<Result<OAuthInitiationResult, Error>>(new ValidationError
            {
                Message = "Invalid redirect URI format",
                Code = "AUTH002",
                Errors = new Dictionary<string, string[]>
                {
                    [nameof(redirectUri)] = ["Redirect URI must be a valid absolute URI"]
                }
            });
        }

        // Generate PKCE code verifier (43-128 characters, base64url)
        var codeVerifier = GenerateCodeVerifier();

        // Generate state if not provided (for CSRF protection)
        var finalState = state ?? Guid.NewGuid().ToString("N");

        // Generate authorization URL (PKCE challenge is generated by service)
        var authorizationUrl = gitHubOAuthService.GetAuthorizationUrl(
            codeVerifier: codeVerifier,
            state: finalState,
            redirectUri: redirectUri);

        return Task.FromResult<Result<OAuthInitiationResult, Error>>(new OAuthInitiationResult(
            AuthorizationUrl: authorizationUrl,
            CodeVerifier: codeVerifier,
            State: finalState));
    }

    /// <summary>
    /// Generates a cryptographically secure code verifier for PKCE.
    /// </summary>
    private static string GenerateCodeVerifier()
    {
        var bytes = new byte[32]; // 32 bytes = 43 base64url characters
        RandomNumberGenerator.Fill(bytes);
        return Convert.ToBase64String(bytes)
            .TrimEnd('=')
            .Replace('+', '-')
            .Replace('/', '_');
    }
}
