CREATE TABLE [dbo].[Users]
(
    [Id] INT NOT NULL IDENTITY(1,1),
    [GitHubUserId] BIGINT NOT NULL UNIQUE,
    [Username] NVARCHAR(100) NOT NULL,
    [Email] NVARCHAR(256) NULL,
    [AvatarUrl] NVARCHAR(500) NULL,
    [CreatedAt] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    [UpdatedAt] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC),
    INDEX [IX_Users_GitHubUserId] NONCLUSTERED ([GitHubUserId] ASC),
    INDEX [IX_Users_Username] NONCLUSTERED ([Username] ASC)
);
