using DevQualX.Functional;

namespace DevQualX.Domain.Infrastructure;

/// <summary>
/// Service for GitHub OAuth authentication flow.
/// Handles authorization URL generation and code-to-token exchange.
/// </summary>
public interface IGitHubOAuthService
{
    /// <summary>
    /// Generates the GitHub OAuth authorization URL with PKCE.
    /// </summary>
    /// <param name="codeVerifier">PKCE code verifier (generated by caller, stored in session).</param>
    /// <param name="state">Anti-CSRF state token (generated by caller, stored in session).</param>
    /// <param name="redirectUri">OAuth callback URI (must match GitHub App configuration).</param>
    /// <returns>Authorization URL to redirect user to.</returns>
    string GetAuthorizationUrl(string codeVerifier, string state, string redirectUri);

    /// <summary>
    /// Exchanges OAuth authorization code for access token.
    /// </summary>
    /// <param name="code">Authorization code from GitHub callback.</param>
    /// <param name="codeVerifier">PKCE code verifier (from session).</param>
    /// <param name="redirectUri">OAuth callback URI (must match authorization request).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Success with access token, or failure with error.</returns>
    Task<Result<string, Error>> ExchangeCodeForTokenAsync(
        string code, 
        string codeVerifier, 
        string redirectUri, 
        CancellationToken cancellationToken = default);
}
